languageCode = "en-us"
title = "CryptoLearn"
baseURL = "https://cryptolearn.github.io/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Documentation for the **Cupper** documentation builder, built with **Cupper** itself."
  codePenUser = "Heydon"
