languageCode = "en-us"
title = "CryptoLearn"
baseURL = "https://victim1307.github.io/cryptolearn"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "A place to learn about cryptography from 0"
  codePenUser = "Heydon"
